/* tslint:disable */
/* eslint-disable */
/**
 * Valkyrie
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CancelExecutionJob200Response
 */
export interface CancelExecutionJob200Response {
    /**
     * 
     * @type {string}
     * @memberof CancelExecutionJob200Response
     */
    'message': string;
}
/**
 * Configuration for a sandbox environment request
 * @export
 * @interface CreateSandbox
 */
export interface CreateSandbox {
    /**
     * Nix flake configuration for the sandbox environment
     * @type {string}
     * @memberof CreateSandbox
     */
    'nix_flake'?: string;
    /**
     * List of programming languages required in the sandbox
     * @type {Array<string>}
     * @memberof CreateSandbox
     */
    'languages'?: Array<string>;
    /**
     * List of system-level dependencies needed in the sandbox
     * @type {Array<string>}
     * @memberof CreateSandbox
     */
    'system_dependencies'?: Array<string>;
    /**
     * List of services to be added to the sandbox
     * @type {Array<string>}
     * @memberof CreateSandbox
     */
    'services'?: Array<string>;
}
/**
 * 
 * @export
 * @interface CreateSandbox200Response
 */
export interface CreateSandbox200Response {
    /**
     * 
     * @type {string}
     * @memberof CreateSandbox200Response
     */
    'result': string;
    /**
     * 
     * @type {number}
     * @memberof CreateSandbox200Response
     */
    'sandboxId': number;
    /**
     * 
     * @type {string}
     * @memberof CreateSandbox200Response
     */
    'sandboxStatusSSE'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSandbox200Response
     */
    'sandboxStatusWS'?: string;
}
/**
 * 
 * @export
 * @interface EnvironmentVariable
 */
export interface EnvironmentVariable {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentVariable
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentVariable
     */
    'value'?: string;
}
/**
 * 
 * @export
 * @interface Execute200Response
 */
export interface Execute200Response {
    /**
     * 
     * @type {number}
     * @memberof Execute200Response
     */
    'jobId': number;
    /**
     * 
     * @type {string}
     * @memberof Execute200Response
     */
    'events': string;
    /**
     * 
     * @type {string}
     * @memberof Execute200Response
     */
    'websocket': string;
}
/**
 * 
 * @export
 * @interface ExecutionConfig
 */
export interface ExecutionConfig {
    /**
     * Represents the worker provider.
     * @type {string}
     * @memberof ExecutionConfig
     */
    'WORKER_PROVIDER': string;
    /**
     * Represents the concurrency level for the worker.
     * @type {number}
     * @memberof ExecutionConfig
     */
    'WORKER_CONCURRENCY': number;
    /**
     * Represents the buffer size for the worker.
     * @type {number}
     * @memberof ExecutionConfig
     */
    'WORKER_BUFFER_SIZE': number;
    /**
     * Represents the task timeout.
     * @type {number}
     * @memberof ExecutionConfig
     */
    'WORKER_MAX_TASK_TIMEOUT': number;
    /**
     * Represents the polling frequency for the worker in seconds.
     * @type {number}
     * @memberof ExecutionConfig
     */
    'WORKER_POLL_FREQ': number;
    /**
     * Represents the runtime for the worker in seconds.
     * @type {string}
     * @memberof ExecutionConfig
     */
    'WORKER_RUNTIME': string;
    /**
     * Represents the log level.
     * @type {string}
     * @memberof ExecutionConfig
     */
    'LOG_LEVEL': string;
    /**
     * Represents the base directory for the system provider.
     * @type {string}
     * @memberof ExecutionConfig
     */
    'SYSTEM_PROVIDER_BASE_DIR'?: string;
    /**
     * Represents whether to clean up directories created by the system provider.
     * @type {boolean}
     * @memberof ExecutionConfig
     */
    'SYSTEM_PROVIDER_CLEAN_UP'?: boolean;
}
/**
 * 
 * @export
 * @interface ExecutionEnvironmentSpec
 */
export interface ExecutionEnvironmentSpec {
    /**
     * 
     * @type {Array<EnvironmentVariable>}
     * @memberof ExecutionEnvironmentSpec
     */
    'environment_variables'?: Array<EnvironmentVariable>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExecutionEnvironmentSpec
     */
    'languageDependencies'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExecutionEnvironmentSpec
     */
    'systemDependencies'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ExecutionEnvironmentSpec
     */
    'setup'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ExecutionEnvironmentSpec
     */
    'secrets'?: { [key: string]: string; };
}
/**
 * 
 * @export
 * @interface ExecutionRequest
 */
export interface ExecutionRequest {
    /**
     * 
     * @type {ExecutionEnvironmentSpec}
     * @memberof ExecutionRequest
     */
    'environment'?: ExecutionEnvironmentSpec;
    /**
     * 
     * @type {string}
     * @memberof ExecutionRequest
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionRequest
     */
    'language'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionRequest
     */
    'version'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExecutionRequest
     */
    'max_retries'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExecutionRequest
     */
    'timeout'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExecutionRequest
     */
    'cmdLineArgs'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionRequest
     */
    'compilerArgs'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionRequest
     */
    'command'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionRequest
     */
    'files'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionRequest
     */
    'input'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionRequest
     */
    'extension'?: string;
}
/**
 * 
 * @export
 * @interface ExecutionResult
 */
export interface ExecutionResult {
    /**
     * 
     * @type {number}
     * @memberof ExecutionResult
     */
    'jobId': number;
    /**
     * 
     * @type {string}
     * @memberof ExecutionResult
     */
    'script': string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionResult
     */
    'flake': string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionResult
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionResult
     */
    'started_at': string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionResult
     */
    'updated_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExecutionResult
     */
    'execId': number;
    /**
     * 
     * @type {string}
     * @memberof ExecutionResult
     */
    'finished_at': string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionResult
     */
    'exec_logs': string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionResult
     */
    'nix_logs'?: string;
}
/**
 * 
 * @export
 * @interface FetchFlake200Response
 */
export interface FetchFlake200Response {
    /**
     * 
     * @type {string}
     * @memberof FetchFlake200Response
     */
    'flake': string;
}
/**
 * 
 * @export
 * @interface GetAllExecutionJobs200Response
 */
export interface GetAllExecutionJobs200Response {
    /**
     * 
     * @type {Array<Job>}
     * @memberof GetAllExecutionJobs200Response
     */
    'jobs': Array<Job>;
    /**
     * 
     * @type {PaginationResponse}
     * @memberof GetAllExecutionJobs200Response
     */
    'pagination': PaginationResponse;
}
/**
 * 
 * @export
 * @interface GetAllExecutions200Response
 */
export interface GetAllExecutions200Response {
    /**
     * 
     * @type {Array<ExecutionResult>}
     * @memberof GetAllExecutions200Response
     */
    'executions': Array<ExecutionResult>;
    /**
     * 
     * @type {PaginationResponse}
     * @memberof GetAllExecutions200Response
     */
    'pagination': PaginationResponse;
}
/**
 * 
 * @export
 * @interface GetAllLanguages200Response
 */
export interface GetAllLanguages200Response {
    /**
     * 
     * @type {Array<LanguageResponse>}
     * @memberof GetAllLanguages200Response
     */
    'languages': Array<LanguageResponse>;
}
/**
 * 
 * @export
 * @interface GetAllVersions200Response
 */
export interface GetAllVersions200Response {
    /**
     * 
     * @type {Array<LanguageVersionResponse>}
     * @memberof GetAllVersions200Response
     */
    'languageVersions': Array<LanguageVersionResponse>;
}
/**
 * 
 * @export
 * @interface GetLanguageById200Response
 */
export interface GetLanguageById200Response {
    /**
     * 
     * @type {LanguageResponse}
     * @memberof GetLanguageById200Response
     */
    'language': LanguageResponse;
}
/**
 * 
 * @export
 * @interface GetLanguageVersionById200Response
 */
export interface GetLanguageVersionById200Response {
    /**
     * 
     * @type {LanguageVersionResponse}
     * @memberof GetLanguageVersionById200Response
     */
    'language': LanguageVersionResponse;
}
/**
 * @type GetSandbox200Response
 * @export
 */
export type GetSandbox200Response = Sandbox | SandboxState;

/**
 * 
 * @export
 * @interface GetVersion200Response
 */
export interface GetVersion200Response {
    /**
     * 
     * @type {string}
     * @memberof GetVersion200Response
     */
    'version': string;
}
/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    'jobId': number;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    'script': string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    'flake': string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    'started_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    'updated_at'?: string;
}
/**
 * 
 * @export
 * @interface Language
 */
export interface Language {
    /**
     * Name of the language.
     * @type {string}
     * @memberof Language
     */
    'name': string;
    /**
     * File extension for the language.
     * @type {string}
     * @memberof Language
     */
    'extension': string;
    /**
     * Monaco editor language identifier.
     * @type {string}
     * @memberof Language
     */
    'monaco_language': string;
    /**
     * Default code for the language.
     * @type {string}
     * @memberof Language
     */
    'default_code': string;
    /**
     * The default template for the language
     * @type {string}
     * @memberof Language
     */
    'template': string;
}
/**
 * 
 * @export
 * @interface LanguageResponse
 */
export interface LanguageResponse {
    /**
     * 
     * @type {string}
     * @memberof LanguageResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof LanguageResponse
     */
    'extension': string;
    /**
     * 
     * @type {string}
     * @memberof LanguageResponse
     */
    'monaco_language': string;
    /**
     * 
     * @type {string}
     * @memberof LanguageResponse
     */
    'default_code': string;
    /**
     * The default template for the language
     * @type {string}
     * @memberof LanguageResponse
     */
    'template': string;
    /**
     * Unique identifier for the language version
     * @type {number}
     * @memberof LanguageResponse
     */
    'id': number;
}
/**
 * 
 * @export
 * @interface LanguageVersion
 */
export interface LanguageVersion {
    /**
     * Reference to the parent language
     * @type {number}
     * @memberof LanguageVersion
     */
    'language_id': number;
    /**
     * Version identifier of the language
     * @type {string}
     * @memberof LanguageVersion
     */
    'version': string;
    /**
     * Name of the Nix package
     * @type {string}
     * @memberof LanguageVersion
     */
    'nix_package_name': string;
    /**
     * 
     * @type {string}
     * @memberof LanguageVersion
     */
    'template': string;
    /**
     * Search query string
     * @type {string}
     * @memberof LanguageVersion
     */
    'search_query': string;
    /**
     * Whether this is the default version of the language
     * @type {boolean}
     * @memberof LanguageVersion
     */
    'default_version': boolean;
}
/**
 * 
 * @export
 * @interface LanguageVersionResponse
 */
export interface LanguageVersionResponse {
    /**
     * Reference to the parent language
     * @type {number}
     * @memberof LanguageVersionResponse
     */
    'language_id': number;
    /**
     * Version identifier of the language
     * @type {string}
     * @memberof LanguageVersionResponse
     */
    'version': string;
    /**
     * Name of the Nix package
     * @type {string}
     * @memberof LanguageVersionResponse
     */
    'nix_package_name': string;
    /**
     * 
     * @type {string}
     * @memberof LanguageVersionResponse
     */
    'template': string;
    /**
     * Search query string
     * @type {string}
     * @memberof LanguageVersionResponse
     */
    'search_query': string;
    /**
     * Whether this is the default version of the language
     * @type {boolean}
     * @memberof LanguageVersionResponse
     */
    'default_version': boolean;
    /**
     * Unique identifier for the language version
     * @type {number}
     * @memberof LanguageVersionResponse
     */
    'id': number;
}
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface Package
 */
export interface Package {
    /**
     * Name of the package
     * @type {string}
     * @memberof Package
     */
    'name': string;
    /**
     * Version of the package
     * @type {string}
     * @memberof Package
     */
    'version': string;
}
/**
 * 
 * @export
 * @interface PaginationResponse
 */
export interface PaginationResponse {
    /**
     * Represents the total number of items.
     * @type {number}
     * @memberof PaginationResponse
     */
    'total': number;
    /**
     * Represents the number of items per page.
     * @type {number}
     * @memberof PaginationResponse
     */
    'limit': number;
    /**
     * Represents the start of the cursor
     * @type {number}
     * @memberof PaginationResponse
     */
    'cursor': number;
}
/**
 * 
 * @export
 * @interface Sandbox
 */
export interface Sandbox {
    /**
     * 
     * @type {number}
     * @memberof Sandbox
     */
    'sandboxId': number;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    'URL': string;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    'agentURL': string;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    'created_at': string;
}
/**
 * 
 * @export
 * @interface SandboxState
 */
export interface SandboxState {
    /**
     * 
     * @type {number}
     * @memberof SandboxState
     */
    'sandboxId': number;
    /**
     * 
     * @type {string}
     * @memberof SandboxState
     */
    'state': string;
}
/**
 * 
 * @export
 * @interface SearchSystemPackages200Response
 */
export interface SearchSystemPackages200Response {
    /**
     * 
     * @type {Array<Package>}
     * @memberof SearchSystemPackages200Response
     */
    'packages': Array<Package>;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Cancel Execution Job
         * @summary Cancel Execution Job
         * @param {number} jobId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelExecutionJob: async (jobId: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('cancelExecutionJob', 'jobId', jobId)
            const localVarPath = `/executions/jobs/{JobId}`
                .replace(`{${"JobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a sandbox
         * @summary Create a sandbox
         * @param {string} [xAuthToken] Authentication token
         * @param {CreateSandbox} [createSandbox] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSandbox: async (xAuthToken?: string, createSandbox?: CreateSandbox, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sandbox`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSandbox, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete execution job
         * @summary Delete execution job
         * @param {number} jobId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteExecutionJob: async (jobId: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('deleteExecutionJob', 'jobId', jobId)
            const localVarPath = `/executions/jobs/{JobId}`
                .replace(`{${"JobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Execute a script
         * @summary Execute a script
         * @param {ExecutionRequest} executionRequest 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        execute: async (executionRequest: ExecutionRequest, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'executionRequest' is not null or undefined
            assertParamExists('execute', 'executionRequest', executionRequest)
            const localVarPath = `/executions/execute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(executionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetches flake of a given job
         * @summary Fetch Flake
         * @param {number} jobId Job ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchFlake: async (jobId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('fetchFlake', 'jobId', jobId)
            const localVarPath = `/flake/{jobId}`
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all execution jobs
         * @summary Get all execution jobs
         * @param {number} [cursor] The current position of the cursor
         * @param {number} [limit] The limit for the records
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllExecutionJobs: async (cursor?: number, limit?: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/jobs/execution`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all executions
         * @summary Get all executions
         * @param {number} [cursor] The current position of the cursor
         * @param {number} [limit] The limit for the records
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllExecutions: async (cursor?: number, limit?: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/executions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a list of all language versions from the database.
         * @summary Get all language versions
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLanguageVersions: async (xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/language-versions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a list of all languages from the database.
         * @summary Get all languages
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLanguages: async (xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/languages`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a list of all language versions from the database.
         * @summary Get all language versions
         * @param {number} id The ID of the language to retrieve versions.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllVersions: async (id: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getAllVersions', 'id', id)
            const localVarPath = `/languages/{id}/versions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get execution config
         * @summary Get execution config
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutionConfig: async (xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/execution/config`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get execution job
         * @summary Get execution job
         * @param {number} jobId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutionJobById: async (jobId: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getExecutionJobById', 'jobId', jobId)
            const localVarPath = `/executions/jobs/{JobId}`
                .replace(`{${"JobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get execution result by id
         * @summary Get execution result by id
         * @param {number} execId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutionResultById: async (execId: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'execId' is not null or undefined
            assertParamExists('getExecutionResultById', 'execId', execId)
            const localVarPath = `/executions/{execId}`
                .replace(`{${"execId"}}`, encodeURIComponent(String(execId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get executions of given job
         * @summary Get executions of given job
         * @param {number} jobId 
         * @param {number} [cursor] The current position of the cursor
         * @param {number} [limit] The limit for the records
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutionsForJob: async (jobId: number, cursor?: number, limit?: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getExecutionsForJob', 'jobId', jobId)
            const localVarPath = `/jobs/{JobId}/executions`
                .replace(`{${"JobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a language entry from the database using its ID.
         * @summary Get language by ID
         * @param {number} id The ID of the language to retrieve.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLanguageById: async (id: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getLanguageById', 'id', id)
            const localVarPath = `/languages/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a language version entry from the database using its ID.
         * @summary Get language version by ID
         * @param {number} id The ID of the language version to retrieve.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLanguageVersionById: async (id: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getLanguageVersionById', 'id', id)
            const localVarPath = `/language-versions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve Sandbox details
         * @summary Get Sandbox
         * @param {number} sandboxId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSandbox: async (sandboxId: number, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sandboxId' is not null or undefined
            assertParamExists('getSandbox', 'sandboxId', sandboxId)
            const localVarPath = `/sandbox/{sandboxId}`
                .replace(`{${"sandboxId"}}`, encodeURIComponent(String(sandboxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get version
         * @summary Get version
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVersion: async (xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/version`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Health Check
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        health: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search for system packages
         * @summary Search for system packages
         * @param {string} searchString The string to be searched.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchSystemPackages: async (searchString: string, xAuthToken?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchString' is not null or undefined
            assertParamExists('searchSystemPackages', 'searchString', searchString)
            const localVarPath = `/packages`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (searchString !== undefined) {
                localVarQueryParameter['searchString'] = searchString;
            }

            if (xAuthToken != null) {
                localVarHeaderParameter['X-Auth-Token'] = String(xAuthToken);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Cancel Execution Job
         * @summary Cancel Execution Job
         * @param {number} jobId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelExecutionJob(jobId: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancelExecutionJob200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelExecutionJob(jobId, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.cancelExecutionJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a sandbox
         * @summary Create a sandbox
         * @param {string} [xAuthToken] Authentication token
         * @param {CreateSandbox} [createSandbox] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSandbox(xAuthToken?: string, createSandbox?: CreateSandbox, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateSandbox200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSandbox(xAuthToken, createSandbox, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createSandbox']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete execution job
         * @summary Delete execution job
         * @param {number} jobId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteExecutionJob(jobId: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteExecutionJob(jobId, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteExecutionJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Execute a script
         * @summary Execute a script
         * @param {ExecutionRequest} executionRequest 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async execute(executionRequest: ExecutionRequest, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Execute200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.execute(executionRequest, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.execute']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetches flake of a given job
         * @summary Fetch Flake
         * @param {number} jobId Job ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchFlake(jobId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FetchFlake200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchFlake(jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.fetchFlake']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all execution jobs
         * @summary Get all execution jobs
         * @param {number} [cursor] The current position of the cursor
         * @param {number} [limit] The limit for the records
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllExecutionJobs(cursor?: number, limit?: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllExecutionJobs200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllExecutionJobs(cursor, limit, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllExecutionJobs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all executions
         * @summary Get all executions
         * @param {number} [cursor] The current position of the cursor
         * @param {number} [limit] The limit for the records
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllExecutions(cursor?: number, limit?: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllExecutions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllExecutions(cursor, limit, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllExecutions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a list of all language versions from the database.
         * @summary Get all language versions
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllLanguageVersions(xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllVersions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllLanguageVersions(xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllLanguageVersions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a list of all languages from the database.
         * @summary Get all languages
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllLanguages(xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllLanguages200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllLanguages(xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllLanguages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a list of all language versions from the database.
         * @summary Get all language versions
         * @param {number} id The ID of the language to retrieve versions.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllVersions(id: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllVersions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllVersions(id, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllVersions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get execution config
         * @summary Get execution config
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExecutionConfig(xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExecutionConfig>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExecutionConfig(xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getExecutionConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get execution job
         * @summary Get execution job
         * @param {number} jobId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExecutionJobById(jobId: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Job>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExecutionJobById(jobId, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getExecutionJobById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get execution result by id
         * @summary Get execution result by id
         * @param {number} execId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExecutionResultById(execId: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExecutionResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExecutionResultById(execId, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getExecutionResultById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get executions of given job
         * @summary Get executions of given job
         * @param {number} jobId 
         * @param {number} [cursor] The current position of the cursor
         * @param {number} [limit] The limit for the records
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExecutionsForJob(jobId: number, cursor?: number, limit?: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllExecutions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExecutionsForJob(jobId, cursor, limit, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getExecutionsForJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a language entry from the database using its ID.
         * @summary Get language by ID
         * @param {number} id The ID of the language to retrieve.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLanguageById(id: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetLanguageById200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLanguageById(id, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getLanguageById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a language version entry from the database using its ID.
         * @summary Get language version by ID
         * @param {number} id The ID of the language version to retrieve.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLanguageVersionById(id: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetLanguageVersionById200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLanguageVersionById(id, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getLanguageVersionById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve Sandbox details
         * @summary Get Sandbox
         * @param {number} sandboxId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSandbox(sandboxId: number, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSandbox200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSandbox(sandboxId, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSandbox']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get version
         * @summary Get version
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVersion(xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetVersion200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVersion(xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Health Check
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async health(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.health(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.health']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Search for system packages
         * @summary Search for system packages
         * @param {string} searchString The string to be searched.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchSystemPackages(searchString: string, xAuthToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchSystemPackages200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchSystemPackages(searchString, xAuthToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.searchSystemPackages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Cancel Execution Job
         * @summary Cancel Execution Job
         * @param {number} jobId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelExecutionJob(jobId: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<CancelExecutionJob200Response> {
            return localVarFp.cancelExecutionJob(jobId, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a sandbox
         * @summary Create a sandbox
         * @param {string} [xAuthToken] Authentication token
         * @param {CreateSandbox} [createSandbox] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSandbox(xAuthToken?: string, createSandbox?: CreateSandbox, options?: RawAxiosRequestConfig): AxiosPromise<CreateSandbox200Response> {
            return localVarFp.createSandbox(xAuthToken, createSandbox, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete execution job
         * @summary Delete execution job
         * @param {number} jobId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteExecutionJob(jobId: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteExecutionJob(jobId, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Execute a script
         * @summary Execute a script
         * @param {ExecutionRequest} executionRequest 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        execute(executionRequest: ExecutionRequest, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<Execute200Response> {
            return localVarFp.execute(executionRequest, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetches flake of a given job
         * @summary Fetch Flake
         * @param {number} jobId Job ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchFlake(jobId: number, options?: RawAxiosRequestConfig): AxiosPromise<FetchFlake200Response> {
            return localVarFp.fetchFlake(jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all execution jobs
         * @summary Get all execution jobs
         * @param {number} [cursor] The current position of the cursor
         * @param {number} [limit] The limit for the records
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllExecutionJobs(cursor?: number, limit?: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAllExecutionJobs200Response> {
            return localVarFp.getAllExecutionJobs(cursor, limit, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all executions
         * @summary Get all executions
         * @param {number} [cursor] The current position of the cursor
         * @param {number} [limit] The limit for the records
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllExecutions(cursor?: number, limit?: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAllExecutions200Response> {
            return localVarFp.getAllExecutions(cursor, limit, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a list of all language versions from the database.
         * @summary Get all language versions
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLanguageVersions(xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAllVersions200Response> {
            return localVarFp.getAllLanguageVersions(xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a list of all languages from the database.
         * @summary Get all languages
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLanguages(xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAllLanguages200Response> {
            return localVarFp.getAllLanguages(xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a list of all language versions from the database.
         * @summary Get all language versions
         * @param {number} id The ID of the language to retrieve versions.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllVersions(id: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAllVersions200Response> {
            return localVarFp.getAllVersions(id, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Get execution config
         * @summary Get execution config
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutionConfig(xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<ExecutionConfig> {
            return localVarFp.getExecutionConfig(xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Get execution job
         * @summary Get execution job
         * @param {number} jobId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutionJobById(jobId: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<Job> {
            return localVarFp.getExecutionJobById(jobId, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Get execution result by id
         * @summary Get execution result by id
         * @param {number} execId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutionResultById(execId: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<ExecutionResult> {
            return localVarFp.getExecutionResultById(execId, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Get executions of given job
         * @summary Get executions of given job
         * @param {number} jobId 
         * @param {number} [cursor] The current position of the cursor
         * @param {number} [limit] The limit for the records
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExecutionsForJob(jobId: number, cursor?: number, limit?: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAllExecutions200Response> {
            return localVarFp.getExecutionsForJob(jobId, cursor, limit, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a language entry from the database using its ID.
         * @summary Get language by ID
         * @param {number} id The ID of the language to retrieve.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLanguageById(id: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetLanguageById200Response> {
            return localVarFp.getLanguageById(id, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a language version entry from the database using its ID.
         * @summary Get language version by ID
         * @param {number} id The ID of the language version to retrieve.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLanguageVersionById(id: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetLanguageVersionById200Response> {
            return localVarFp.getLanguageVersionById(id, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve Sandbox details
         * @summary Get Sandbox
         * @param {number} sandboxId 
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSandbox(sandboxId: number, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetSandbox200Response> {
            return localVarFp.getSandbox(sandboxId, xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Get version
         * @summary Get version
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVersion(xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetVersion200Response> {
            return localVarFp.getVersion(xAuthToken, options).then((request) => request(axios, basePath));
        },
        /**
         * Health Check
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        health(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.health(options).then((request) => request(axios, basePath));
        },
        /**
         * Search for system packages
         * @summary Search for system packages
         * @param {string} searchString The string to be searched.
         * @param {string} [xAuthToken] Authentication token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchSystemPackages(searchString: string, xAuthToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<SearchSystemPackages200Response> {
            return localVarFp.searchSystemPackages(searchString, xAuthToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Cancel Execution Job
     * @summary Cancel Execution Job
     * @param {number} jobId 
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public cancelExecutionJob(jobId: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).cancelExecutionJob(jobId, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a sandbox
     * @summary Create a sandbox
     * @param {string} [xAuthToken] Authentication token
     * @param {CreateSandbox} [createSandbox] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createSandbox(xAuthToken?: string, createSandbox?: CreateSandbox, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createSandbox(xAuthToken, createSandbox, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete execution job
     * @summary Delete execution job
     * @param {number} jobId 
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteExecutionJob(jobId: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteExecutionJob(jobId, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Execute a script
     * @summary Execute a script
     * @param {ExecutionRequest} executionRequest 
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public execute(executionRequest: ExecutionRequest, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).execute(executionRequest, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetches flake of a given job
     * @summary Fetch Flake
     * @param {number} jobId Job ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public fetchFlake(jobId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).fetchFlake(jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all execution jobs
     * @summary Get all execution jobs
     * @param {number} [cursor] The current position of the cursor
     * @param {number} [limit] The limit for the records
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAllExecutionJobs(cursor?: number, limit?: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllExecutionJobs(cursor, limit, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all executions
     * @summary Get all executions
     * @param {number} [cursor] The current position of the cursor
     * @param {number} [limit] The limit for the records
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAllExecutions(cursor?: number, limit?: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllExecutions(cursor, limit, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a list of all language versions from the database.
     * @summary Get all language versions
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAllLanguageVersions(xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllLanguageVersions(xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a list of all languages from the database.
     * @summary Get all languages
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAllLanguages(xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllLanguages(xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a list of all language versions from the database.
     * @summary Get all language versions
     * @param {number} id The ID of the language to retrieve versions.
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAllVersions(id: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllVersions(id, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get execution config
     * @summary Get execution config
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getExecutionConfig(xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getExecutionConfig(xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get execution job
     * @summary Get execution job
     * @param {number} jobId 
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getExecutionJobById(jobId: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getExecutionJobById(jobId, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get execution result by id
     * @summary Get execution result by id
     * @param {number} execId 
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getExecutionResultById(execId: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getExecutionResultById(execId, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get executions of given job
     * @summary Get executions of given job
     * @param {number} jobId 
     * @param {number} [cursor] The current position of the cursor
     * @param {number} [limit] The limit for the records
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getExecutionsForJob(jobId: number, cursor?: number, limit?: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getExecutionsForJob(jobId, cursor, limit, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a language entry from the database using its ID.
     * @summary Get language by ID
     * @param {number} id The ID of the language to retrieve.
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getLanguageById(id: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getLanguageById(id, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a language version entry from the database using its ID.
     * @summary Get language version by ID
     * @param {number} id The ID of the language version to retrieve.
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getLanguageVersionById(id: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getLanguageVersionById(id, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve Sandbox details
     * @summary Get Sandbox
     * @param {number} sandboxId 
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getSandbox(sandboxId: number, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSandbox(sandboxId, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get version
     * @summary Get version
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getVersion(xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getVersion(xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Health Check
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public health(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).health(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search for system packages
     * @summary Search for system packages
     * @param {string} searchString The string to be searched.
     * @param {string} [xAuthToken] Authentication token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchSystemPackages(searchString: string, xAuthToken?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).searchSystemPackages(searchString, xAuthToken, options).then((request) => request(this.axios, this.basePath));
    }
}



